version: '3.3'

services:
  db:
    image: postgres:16.1
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../backend/.env

  web:
    build: ../backend/
    restart: always
    environment:
      - DOCKER_ENV=1
    volumes:
      # - data_value:/app/data/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ../frontend
    restart: always
    volumes:
      - react_build:/react/dist

  nginx:
    image: nginx:1.25.3
    restart: always
    ports:
      - "8241:8241"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - react_build:/var/www/react
    depends_on:
      - frontend
      - web


volumes:
  static_value:
  media_value:
  # data_value:
  react_build:
